In [1]:
import numpy as np

sıfırdan array oluşturma


In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [5]:
np.full((3,5), 3)


array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [6]:
np.arange(0, 31 ,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [7]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [8]:
 b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
    

In [9]:
b


array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [10]:
b[[1, 0, 1, 0]][:,[0,1,2,0]]

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

Row Indexing (b[[1, 0, 1, 0]]):

This part of the indexing is selecting rows from the array b based on the provided list of row indices [1, 0, 1, 0]. The resulting array would have the rows from the original array in the order specified by the list.

The first row is the row at index 1: [4, 5, 6].
The second row is the row at index 0: [1.5, 2, 3].
The third row is again the row at index 1: [4, 5, 6].
The fourth row is again the row at index 0: [1.5, 2, 3].

Satır İndeksleme (b[[1, 0, 1, 0]]):

Bu kısım, belirtilen satır indisleri [1, 0, 1, 0] kullanılarak diziden satırları seçiyor. Sonuç dizisi, orijinal dizide belirtilen sırayla satırları içerir.

İlk satır, 1. indexteki satırdır: [4, 5, 6].
İkinci satır, 0. indexteki satırdır: [1.5, 2, 3].
Üçüncü satır, tekrar 1. indexteki satırdır: [4, 5, 6].
Dördüncü satır, tekrar 0. indexteki satırdır: [1.5, 2, 3].

[[4. 5. 6.]
 [1.5 2. 3.]
 [4. 5. 6.]
 [1.5 2. 3.]]

Column Indexing ([:, [0, 1, 2, 0]]):

This part of the indexing is selecting columns from the array obtained from the previous step based on the provided list of column indices [0, 1, 2, 0]. The resulting array would have columns from the original array in the order specified by the list.

The first column is the column at index 0: [4, 1.5, 4, 1.5].
The second column is the column at index 1: [5, 2, 5, 2].
The third column is the column at index 2: [6, 3, 6, 3].
The fourth column is again the column at index 0: [4, 1.5, 4, 1.5].

Sütun İndeksleme ([:, [0, 1, 2, 0]]):

Bu kısım, önceki adımdan elde edilen diziden belirtilen sütun indisleri [0, 1, 2, 0] kullanılarak sütunları seçiyor. Sonuç dizisi, orijinal diziden belirtilen sırayla sütunları içerir.

İlk sütun, 0. indexteki sütundur: [4, 1.5, 4, 1.5].
İkinci sütun, 1. indexteki sütundur: [5, 2, 5, 2].
Üçüncü sütun, 2. indexteki sütundur: [6, 3, 6, 3].
Dördüncü sütun, tekrar 0. indexteki sütundur: [4, 1.5, 4, 1.5].


 
 
 [[4. 5. 6. 4.]
 [1.5 2. 3. 1.5]
 [4. 5. 6. 4.]
 [1.5 2. 3. 1.5]]



So, the final result is a 4x4 array where rows and columns are selected based on the specified indices. The row indices are [1, 0, 1, 0], and the column indices are [0, 1, 2, 0]. This advanced indexing allows you to extract and rearrange elements from an array in a more flexible way.

Sonuç olarak, sonuç 4x4 boyutunda bir dizi olup, satır ve sütunlar belirtilen indislerle seçilmiştir. Satır indisleri [1, 0, 1, 0] ve sütun indisleri [0, 1, 2, 0]. Bu gelişmiş indeksleme, bir diziden elemanları çıkarmak ve düzenlemek için daha esnek bir yöntem sunar.

Numpy açık kaynaklı bir Python kütüphanesidir. Bu kütüphane veri bilimcileri için gereklidir. Pandas, Scipy gibi diğer bazı temel kütüphaneler Numpy kütüphanesi üzerine inşa edilmiştir. Numpy belgelerinde Numpy şu şekilde tanımlanır:

NumPy, Python'da bilimsel hesaplama için temel pakettir. Çok boyutlu bir dizi nesnesi, çeşitli türetilmiş nesneler (maskeli diziler ve matrisler gibi) ve diziler üzerinde matematiksel, mantıksal, şekil manipülasyonu, sıralama, seçme, G/Ç  , ayrık Fourier dönüşümleri, temel doğrusal cebir, temel istatistiksel işlemler, rastgele simülasyon ve çok daha fazlası dahil olmak üzere hızlı işlemler için çeşitli rutinler sağlayan bir Python kütüphanesidir.

In [11]:
import numpy as np


In [12]:
np.random.normal(10,4,(3,4)) #ortalaması 10, standart sapması 4

array([[12.71222892, 13.3335618 , 15.8037623 , 13.30724042],
       [14.93524153,  9.19907547, 12.39569511,  3.53337909],
       [ 8.47933218,  9.01659321,  6.66995201,  8.27720446]])

In [13]:
np.random.randint(0,10,(3,3))

array([[4, 6, 3],
       [6, 2, 5],
       [5, 3, 2]])

In [14]:
np.random.randint(10, size = 10)

array([0, 6, 2, 5, 1, 7, 3, 0, 2, 1])

In [15]:
a = np.random.randint(10, size=10)
a

array([0, 9, 9, 9, 6, 0, 0, 9, 6, 1])

In [16]:
a.ndim


1

In [17]:
a.shape

(10,)

In [18]:
a.shape[0]

10

In [19]:
b = np.random.randint(10, size =(3,5))
b

array([[6, 0, 6, 4, 8],
       [4, 9, 4, 3, 5],
       [7, 9, 9, 2, 1]])

In [20]:
b.ndim

2

In [21]:
b.shape

(3, 5)

In [22]:
b.shape[1]

5

In [23]:
b.shape[0]

3

In [24]:
b.size

15

In [25]:
b.dtype

dtype('int32')

In [26]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
a = np.arange(1,10)

In [29]:
a.ndim


1

In [30]:
a.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [31]:
a.ndim

1

In [32]:
b = a.reshape((1,9))
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [33]:
b.ndim

2

In [34]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [35]:
np.concatenate([x , y])

array([1, 2, 3, 4, 5, 6])

In [36]:
z = np.array([7, 8 , 9])

In [37]:
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a = np.array([[1, 2, 3],
             [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [40]:
np.concatenate([a,a], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [41]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [42]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])
x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [43]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [44]:
a, b, c = np.split(x, [3,5])

In [45]:
a

array([1, 2, 3])

In [46]:
b

array([99, 99])

In [47]:
c

array([3, 2, 1])

In [48]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])

In [49]:
x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [50]:
np.split(x , [ 3, 5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [51]:
a, b , c = np.split(x , [ 3, 5])

In [52]:
a


array([1, 2, 3])

In [53]:
b

array([99, 99])

In [54]:
c

array([3, 2, 1])

In [56]:
m = np.arange(16).reshape(4,4)

In [57]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [58]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [59]:
ust, alt = np.vsplit(m, [2])

In [60]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [61]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [63]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [64]:
sag, sol = np.hsplit(m, [2])

In [65]:
sag


array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [66]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [67]:
v  = np.array([2, 1, 4, 3, 5])
v

array([2, 1, 4, 3, 5])

In [68]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [69]:
v.sort()

In [70]:
v

array([1, 2, 3, 4, 5])

In [73]:
m  = np.random.normal(20, 5,(3,3))
m

array([[25.52776316, 16.72443214, 23.52907591],
       [22.26063197, 16.80005944, 28.83208477],
       [30.5752915 , 13.72442034, 14.7647442 ]])

In [75]:
np.sort(m, axis = 0) #axis 0 vertical yönünde

array([[22.26063197, 13.72442034, 14.7647442 ],
       [25.52776316, 16.72443214, 23.52907591],
       [30.5752915 , 16.80005944, 28.83208477]])

In [76]:
np.sort(m, axis = 1) #axis 1 horizantal yönünde

array([[16.72443214, 23.52907591, 25.52776316],
       [16.80005944, 22.26063197, 28.83208477],
       [13.72442034, 14.7647442 , 30.5752915 ]])

index ile elemanlara erişmek


In [1]:
import numpy as np


In [4]:
a =  np.random.randint(10, size =  10)
a

array([4, 2, 9, 0, 1, 0, 0, 5, 3, 2])

In [5]:
a[0]


4

In [6]:
a[-1]


2

In [8]:
a[0] = 100
a

array([100,   2,   9,   0,   1,   0,   0,   5,   3,   2])

In [9]:
m =  np.random.randint(10, size =  (3,5))

In [10]:
m

array([[7, 8, 0, 5, 2],
       [0, 0, 5, 8, 7],
       [2, 3, 5, 5, 7]])

In [11]:
m[0,0]

7

In [12]:
m[1,1]


0

In [13]:
m[1,4]

7

In [14]:
m[1,4]=99
m

array([[ 7,  8,  0,  5,  2],
       [ 0,  0,  5,  8, 99],
       [ 2,  3,  5,  5,  7]])

In [15]:
m[1,4] = 2.2

In [16]:
m

array([[7, 8, 0, 5, 2],
       [0, 0, 5, 8, 2],
       [2, 3, 5, 5, 7]])

In [17]:
a[0:3]

array([100,   2,   9])

In [18]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [19]:
a[0:3]

array([20, 21, 22])

In [20]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [21]:
a[1::2]

array([21, 23, 25, 27, 29])

In [22]:
a[0::2]


array([20, 22, 24, 26, 28])

In [23]:
 help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [26]:
def square(a):
    """ Return the square of a"""
    return a ** 2

In [27]:
square?

Signature: square(a)
Docstring: Return the square of a
File:      c:\users\90530\appdata\local\temp\ipykernel_2372\860310146.py
Type:      function

In [28]:
square??


Signature: square(a)
Source:   
def square(a):
    """ Return the square of a"""
    return a ** 2
File:      c:\users\90530\appdata\local\temp\ipykernel_2372\860310146.py
Type:      function

In [29]:
L = [1,2,3]

In [30]:
*Warning?

BytesWarning
DeprecationWarning
EncodingWarning
FutureWarning
ImportWarning
PendingDeprecationWarning
ResourceWarning
RuntimeWarning
SyntaxWarning
UnicodeWarning
UserWarning
Warning

In [31]:
str.*find*?

str.find
str.rfind

In [32]:
%run?

Docstring:
Run the named file inside IPython as a program.

Usage::

  %run [-n -i -e -G]
       [( -t [-N<N>] | -d [-b<N>] | -p [profile options] )]
       ( -m mod | filename ) [args]

The filename argument should be either a pure Python script (with
extension ``.py``), or a file with custom IPython syntax (such as
magics). If the latter, the file can be either a script with ``.ipy``
extension, or a Jupyter notebook with ``.ipynb`` extension. When running
a Jupyter notebook, the output from print statements and other
displayed objects will appear in the terminal (even matplotlib figures
will open, if a terminal-compliant backend is being used). Note that,
at the system command line, the ``jupyter run`` command offers similar
functionality for executing notebooks (albeit currently with some
differences in supported options).

Parameters after the filename are passed as command-line arguments to
the program (put in sys.argv). Then, control returns to IPython's
prompt.

This is similar 

In [1]:
import numpy as np

iki boyutlu slice işlemleri

In [3]:
m  = np.random.randint(10, size = (5,5))

In [4]:
m

array([[4, 7, 8, 1, 3],
       [9, 0, 8, 9, 3],
       [5, 2, 4, 6, 2],
       [2, 5, 4, 5, 6],
       [8, 1, 9, 9, 2]])

In [5]:
m[:, 0]

array([4, 9, 5, 2, 8])

In [6]:
m[:, 1]

array([7, 0, 2, 5, 1])

In [7]:
m[:,4]


array([3, 3, 2, 6, 2])

In [8]:
m[0,:]


array([4, 7, 8, 1, 3])

In [9]:
m[1, :]

array([9, 0, 8, 9, 3])

In [10]:
m[0:2, 0:3]

array([[4, 7, 8],
       [9, 0, 8]])

In [11]:
m[::, :2]

array([[4, 7],
       [9, 0],
       [5, 2],
       [2, 5],
       [8, 1]])

In [12]:
m[1:3, 0:2]

array([[9, 0],
       [5, 2]])

In [13]:
a = np.random.randint(10, size = (5,5))
a

array([[6, 3, 4, 1, 0],
       [6, 5, 9, 0, 2],
       [2, 2, 4, 2, 0],
       [6, 8, 4, 7, 7],
       [4, 2, 4, 1, 1]])

In [14]:
alt_a= a[0:3, 0:2]

In [15]:
alt_a[0,0]=9999

In [16]:
alt_a[1,1]=888

In [17]:
alt_a


array([[9999,    3],
       [   6,  888],
       [   2,    2]])

In [18]:
a


array([[9999,    3,    4,    1,    0],
       [   6,  888,    9,    0,    2],
       [   2,    2,    4,    2,    0],
       [   6,    8,    4,    7,    7],
       [   4,    2,    4,    1,    1]])

In [19]:
n =  np.random.randint(10, size = (5,5))
n

array([[4, 0, 1, 1, 0],
       [0, 6, 4, 2, 3],
       [4, 0, 1, 2, 4],
       [7, 3, 7, 4, 8],
       [8, 9, 1, 1, 5]])

In [25]:
alt_b = n[0:3, 0:2].copy() #copy işlemi

In [21]:
alt_b


array([[4, 0],
       [0, 6],
       [4, 0]])

In [22]:
alt_b[0,0]=9999

In [23]:
alt_b

array([[9999,    0],
       [   0,    6],
       [   4,    0]])

In [24]:
n

array([[4, 0, 1, 1, 0],
       [0, 6, 4, 2, 3],
       [4, 0, 1, 2, 4],
       [7, 3, 7, 4, 8],
       [8, 9, 1, 1, 5]])

In [26]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [27]:
v[1]

3

In [28]:
v[3]

9

In [29]:
v[5]

15

In [31]:
[v[1], v[3],v[5]]

[3, 9, 15]

In [32]:
al_getir = [1,3,5]

In [34]:
v[al_getir]

array([ 3,  9, 15])

iki boyutta fancy

In [35]:
m =  np.arange(9).reshape(3,3)

In [36]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
row = np.array([0,1])
col =  np.array([1,2])

In [39]:
m[row, col]

array([1, 5])

basit index ile fancy

In [40]:
m[0, [1,2]]

array([1, 2])

slice ile fancy

In [42]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

fancy index ile elemanlara erişmek

In [43]:
v = np.arange(0,30,3)

In [44]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [45]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [46]:
v > 5

array([False, False, False, False, False])

In [47]:
v < 3

array([ True,  True, False, False, False])

In [48]:
v[v < 3]

array([1, 2])

In [49]:
v[ v > 3]

array([4, 5])

In [50]:
v[v <= 3]

array([1, 2, 3])

In [51]:
v[v >= 3]

array([3, 4, 5])

In [52]:
v[v == 3]

array([3])

In [53]:
v[v != 3]

array([1, 2, 4, 5])

In [54]:
v

array([1, 2, 3, 4, 5])

In [55]:
v * 2

array([ 2,  4,  6,  8, 10])

In [56]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [57]:
v * 5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [58]:
v**2

array([ 1,  4,  9, 16, 25])

In [1]:
import numpy as np

In [2]:
v = np.array([1,2,3,4,5])

In [3]:
v -1 

array([0, 1, 2, 3, 4])

In [4]:
v * 5

array([ 5, 10, 15, 20, 25])

In [5]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [6]:
v*5/10 -1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [8]:
np.subtract(v , 1)

array([0, 1, 2, 3, 4])

In [9]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [10]:
np.multiply(v,1)

array([1, 2, 3, 4, 5])

In [11]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [12]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [13]:
np.absolute(np.array([-3]))

array([3])

In [14]:
np.sin(360)

0.9589157234143065

In [15]:
np.cos(180)

-0.5984600690578581

In [16]:
k = np.array([1,2,3])

In [17]:
np.log(k)

array([0.        , 0.69314718, 1.09861229])

In [18]:
np.log2(k)

array([0.       , 1.       , 1.5849625])

In [19]:
np.log10(k)

array([0.        , 0.30103   , 0.47712125])

In [23]:
np.mean(k, axis = 0)

2.0

In [21]:
k.sum()

6

In [22]:
k.min()


1

5* x0 + x1 = 12

x0 + 3 * x1 = 10

In [24]:
a = np.array([[5,1],[1,3]])

In [25]:
b = np.array([12,10])

In [26]:
x = np.linalg.solve(a,b)

In [27]:
x

array([1.85714286, 2.71428571])