# Pandas DataFrrame Oluşturma


In [1]:
import pandas as pd

In [2]:
l = [1, 2, 39, 67, 90]

In [3]:
l

[1, 2, 39, 67, 90]

In [4]:
pd.DataFrame(l, columns = ["degisken_ismi"])

degisken_ismi
0              1
1              2
2             39
3             67
4             90

In [5]:
import numpy as np
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
pd.DataFrame(m, columns = ["var1", "var2", "var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

### df isimlendirme

In [7]:
df = pd.DataFrame(m, columns = ["var1", "var2", "var3"])

In [9]:
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [11]:
df.columns 

Index(['var1', 'var2', 'var3'], dtype='object')

In [12]:
df.columns = ("deg1", "deg2", "deg3")

In [13]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [14]:
type(df)

pandas.core.frame.DataFrame

In [15]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [16]:
df.shape

(3, 3)

In [17]:
df.ndim

2

In [18]:
df.size

9

In [19]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
type(df.values)

numpy.ndarray

In [21]:
df.head()

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [22]:
df.tail()

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [23]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [24]:
pd.DataFrame(a, columns = ["deg1"])

deg1
0     1
1     2
2     3
3     4
4     5

# Pandas Eleman İşlemleri

In [25]:
import numpy as np
s1 =  np.random.randint(10, size =5)
s2 =  np.random.randint(10, size =5)
s3 =  np.random.randint(10, size =5)

In [26]:
s1

array([1, 9, 5, 6, 4])

numpy array üzerinden dictionary oluşturma

In [28]:
dic = { "var1" : s1, "var2" : s2, "var3" : s3 }

In [29]:
dic

{'var1': array([1, 9, 5, 6, 4]),
 'var2': array([3, 9, 0, 7, 8]),
 'var3': array([6, 1, 1, 7, 6])}

In [30]:
df = pd.DataFrame(dic)
df

var1  var2  var3
0     1     3     6
1     9     9     1
2     5     0     1
3     6     7     7
4     4     8     6

In [31]:
df [0:1]

var1  var2  var3
0     1     3     6

In [32]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [33]:
df.index = ["a", "b", "c", "d", "e"]

In [34]:
df

var1  var2  var3
a     1     3     6
b     9     9     1
c     5     0     1
d     6     7     7
e     4     8     6

In [35]:
df["c" : "e"]

var1  var2  var3
c     5     0     1
d     6     7     7
e     4     8     6

In [37]:
df[2:4]

var1  var2  var3
c     5     0     1
d     6     7     7

#### why the difference in between the results of two slicings shown above:

The difference between df[0:1] and df["c":"e"] in Pandas slicing lies in how Pandas interprets these indexers.

df[0:1]: This selects rows using integer-based indexing. It retrieves the rows from index 0 up to, but not including, index 1. It follows standard Python-style slicing where the end index is exclusive.

df["c":"e"]: This selects rows using label-based indexing. When you slice using labels with this syntax, Pandas includes both the start and end labels in the result. So, it retrieves rows whose indices range from c to e inclusive.

The difference in the results arises because 0:1 in integer-based slicing considers positions, while "c":"e" in label-based slicing considers the labels themselves.

### silme işlemi

In [38]:
df

var1  var2  var3
a     1     3     6
b     9     9     1
c     5     0     1
d     6     7     7
e     4     8     6

In [39]:
df.drop("a", axis = 0)

var1  var2  var3
b     9     9     1
c     5     0     1
d     6     7     7
e     4     8     6

In [41]:
df  #orjinal df de bir değişiklik olmadı

var1  var2  var3
a     1     3     6
b     9     9     1
c     5     0     1
d     6     7     7
e     4     8     6

In [42]:
df.drop("a", axis = 0, inplace= True)

In [44]:
df # satur kalıcı olarak uçar, inplace'in görevi dataframe üzerinde yapılan değişikliğin kalıcı olarak kalmasını sağlamaktır

var1  var2  var3
b     9     9     1
c     5     0     1
d     6     7     7
e     4     8     6

### fancy silme işlemi

In [46]:
liste = ["c", "e"]

In [48]:
df.drop(liste, axis = 0)

var1  var2  var3
b     9     9     1
d     6     7     7

### değişkenler için

In [49]:
df

var1  var2  var3
b     9     9     1
c     5     0     1
d     6     7     7
e     4     8     6

In [50]:
"var1" in df

True

In [51]:
l = ["var1", "var4", "var2"]

In [52]:
for i in l:
    print(i in df)

True
False
True


In [56]:
[i for i in l if i in df]

['var1', 'var2']

In [57]:
df

var1  var2  var3
b     9     9     1
c     5     0     1
d     6     7     7
e     4     8     6

In [58]:
df["var1"]

b    9
c    5
d    6
e    4
Name: var1, dtype: int32

In [61]:
df["var4"] = df["var1"] / df["var2"]  #değişken oluşturma

In [62]:
df

var1  var2  var3      var4
b     9     9     1  1.000000
c     5     0     1       inf
d     6     7     7  0.857143
e     4     8     6  0.500000

### değişken silmek

In [63]:
df.drop("var4", axis = 1)  # axis 0 satırlar  axis 1 sutunlar

var1  var2  var3
b     9     9     1
c     5     0     1
d     6     7     7
e     4     8     6

In [64]:
df

var1  var2  var3      var4
b     9     9     1  1.000000
c     5     0     1       inf
d     6     7     7  0.857143
e     4     8     6  0.500000

In [65]:
df.drop("var4", axis = 1, inplace = True)

In [66]:
df

var1  var2  var3
b     9     9     1
c     5     0     1
d     6     7     7
e     4     8     6

In [67]:
#fancy ile silme işlemi

In [68]:
z = ["var1", "var2"]

In [69]:
df.drop(z, axis = 1)

var3
b     1
c     1
d     7
e     6

## Gözlem ve Değişken Seçimi

In [ ]:
num