![Divider01](images/divider01.png)

> `NumPy modülünü içeri aktaralım`         ![NumPy](images/numpy.png)

In [2]:
import numpy as np

![Divider05](images/divider05.png)

#### Random Fonksiyonu

Numpy, rastgele sayı üretimi için mükemmel işlevlere sahip. Bu işlevler makine öğreniminde, araştırmada veya istatistikte çok faydalıdırlar.

In [3]:
np.random.rand()  # 0 ile 1 arasında bir sayı üretir.

0.4765219302871826

In [4]:
np.random.rand(5)

array([0.88058216, 0.30033015, 0.6412449 , 0.0047758 , 0.9310379 ])

In [5]:
np.random.rand(2, 3)

array([[0.9966529 , 0.58531736, 0.6563333 ],
       [0.98547314, 0.70673376, 0.11218023]])

In [6]:
np.random.randint(25) # 0 ile 25 arasında rastgele bir integer sayı üretir

12

In [7]:
np.random.randint(1, 100, 10) # 1 ile 100 arasında 10 tane rastgele integer üretir

array([26, 21, 98, 50, 85, 83, 90, 95, 83, 76])

In [8]:
np.random.randint(1, 100, (3,3)) #3x3 matris, elemanlar 1-100 arasında

array([[28, 19, 69],
       [10, 54, 45],
       [70, 91,  4]])

In [9]:
np.random.choice([0,1,2,3,4,5,6,7,8,9,10], size=(3,3)) #Bir aralık yerine bir array sağlayabilir ve Numpy'den bu sağladığınız dizideki sayıları kullanarak 3×3'lük bir matris yapmasını isteyebilirsiniz.

array([[7, 0, 3],
       [5, 1, 2],
       [7, 8, 2]])

In [10]:
shuff = np.array([7,6,7,1,0, 11])  #random.shuffle
np.random.shuffle(shuff)
shuff

array([ 7, 11,  7,  0,  6,  1])

![Divider05](images/divider05.png)

#### Save, Load ve  Import 

In [11]:
np.save('shufffile', shuff)

In [12]:
np.load('shufffile.npy')

array([ 7, 11,  7,  0,  6,  1])

In [13]:
filedata = np.genfromtxt('untitled.txt', delimiter=',')
filedata=filedata.astype('int32')
filedata

C:\Users\90530\AppData\Local\Temp\ipykernel_748\3476671791.py:2: RuntimeWarning: invalid value encountered in cast
  filedata=filedata.astype('int32')


array([[-2147483648, -2147483648, -2147483648, ..., -2147483648,
        -2147483648, -2147483648],
       [         16,           1, -2147483648, ..., -2147483648,
        -2147483648,           2],
       [         10,           1, -2147483648, ..., -2147483648,
        -2147483648,           3],
       ...,
       [         22,           2, -2147483648, ..., -2147483648,
        -2147483648,           2],
       [         17,           1, -2147483648, ..., -2147483648,
        -2147483648,           2],
       [         18,           3, -2147483648, ..., -2147483648,
        -2147483648,           2]])

![Divider05](images/divider05.png)


### fancy index again

In [14]:
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [15]:
v[1]

3

In [16]:
v[3]


9

In [17]:
v[5]

15

In [18]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [19]:
al_getir = [1, 3, 5]

In [20]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [21]:
v[al_getir]

array([ 3,  9, 15])

![Divider05](images/divider05.png)

![Divider02](images/divider02.png)

#### iki boyutta fancy

In [22]:
m = np.arange(9).reshape((3,3))

In [23]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
row = np.array([0,1])
col = np.array([1,2])

In [25]:
m[row, col]

array([1, 5])

![Divider05](images/divider05.png)

#### basit index ile fancy index


In [26]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
m[0, [1,2]]

array([1, 2])

In [28]:
m[1, [1,2]]

array([4, 5])

In [29]:
m[2, [1,2]]

array([7, 8])

In [30]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
m[0, [0,1]]

array([0, 1])

In [32]:
m[2, [0,1]]

array([6, 7])

![Divider05](images/divider05.png)

#### slice ile fancy index

In [33]:
m[0: , [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [34]:
m[1, [0,2]]

array([3, 5])

In [35]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
m[1:2, [1,2]]

array([[4, 5]])

In [37]:
m[1:, [1,2]]

array([[4, 5],
       [7, 8]])

![Divider05](images/divider05.png)


![Divider02](images/divider02.png)

### Matematiksel İşlemler - Array Matematiği -  Aritmetik İşlemler, Aggregate Fonksiyonlar, Karşılaştırmalar

Bu bölümde Numpy ile  matematiksel işlemleri göstereceğim. İşlemlerin çoğu kendiliğinden anlaşılmaktadır.

In [38]:
import numpy as np

In [94]:
v = np.array([1, 2, 3, 4, 5])

In [40]:
v + 2

array([3, 4, 5, 6, 7])

In [41]:
v - 1

array([0, 1, 2, 3, 4])

In [42]:
v * 5

array([ 5, 10, 15, 20, 25])

In [43]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [95]:
v ** 2

array([ 1,  4,  9, 16, 25])

In [44]:
v * 5/10 -1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

> #### `#ufunc`

In [46]:
np.subtract(v , 1)

array([0, 1, 2, 3, 4])

In [47]:
np.add(v , 1)

array([2, 3, 4, 5, 6])

In [48]:
np.multiply(v , 4)

array([ 4,  8, 12, 16, 20])

In [49]:
np.divide(v , 3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [50]:
v**2

array([ 1,  4,  9, 16, 25])

In [97]:
np.sqrt(v)  #square root, kare kök

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [51]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [52]:
np.power(v, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [53]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [54]:
np.mod(v , 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [55]:
np.absolute(np.array([-3]))

array([3])

In [56]:
np.sin(360)

0.9589157234143065

In [57]:
np.cos(180)

-0.5984600690578581

In [98]:
np.tan(v)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [58]:
v  = np.array([1, 2, 3])

In [59]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [60]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [61]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

> Şimdi elimizde a ve b olmak üzere iki array/dizi var. Aynı matematiksel işlemleri yapalım. Yine basit ve kendiliğinden anlaşılan,

In [99]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [100]:
b = np.array([3, 4, 5, 6, 7])
b

array([3, 4, 5, 6, 7])

In [101]:
a + b

array([ 4,  6,  8, 10, 12])

In [102]:
a - b

array([-2, -2, -2, -2, -2])

In [103]:
a * b

array([ 3,  8, 15, 24, 35])

In [126]:
5* np.array([1, 2, 3])

array([ 5, 10, 15])

In [104]:
a / b

array([0.33333333, 0.5       , 0.6       , 0.66666667, 0.71428571])

In [105]:
a // b

array([0, 0, 0, 0, 0])

In [106]:
a ** b

array([    1,    16,   243,  4096, 78125])

In [107]:
a.dot(b)

85

a.dot(b) nedir? Bu, element bazında çarpma ve ardından bu şekilde toplama işlemidir,

1*3 + 2*4 + 3*5 + 4*6 + 5*7

aşağıda ki syntax ile de yazabiliriz:

In [108]:
np.dot(a, b)

85

Bu dot işlemini çok boyutlu arraylerde/dizilerde kullanabiliriz. Bunun için iki adet çok boyutlu array oluşturalım,

In [109]:
c = np.array([[3, 5, 7], [2, 4, 8]])
c

array([[3, 5, 7],
       [2, 4, 8]])

In [110]:
d = np.array([[5,3], [7,9], [4, 3]])
d

array([[5, 3],
       [7, 9],
       [4, 3]])

In [111]:
c.dot(d)

array([[78, 75],
       [70, 66]])

In [ ]:
Girişler 2 boyutlu dizi olduğunda 'dot' fonksiyonu matris çarpımı gibi davranır. 
Bu, yalnızca ilk arrayin sütun sayısı ikinci arrayin satır sayısıyla eşleştiğinde 'dot' işlemini gerçekleştirebileceğiniz anlamına gelir.
Matris çarpımının başka bir ifadesi daha vardır:

In [112]:
np.matmul(c, d)

array([[78, 75],
       [70, 66]])

'np.matmul' tek boyutlu dizilerde çalışmaz. Unutmayın, bu çarpma kuralı toplama, çıkarma, bölme gibi diğer işlemlerde geçerli değildir. 
Bir matrisi diğerine eklemek, çıkarmak veya bölmek için aynı şekil ve boyutta dizilere sahip olmanız gerekir.

> #### Numpy ile temel sayısal hesaplamalar


Matematiksel işlemler ile temel hesaplamalar üzerinde biraz daha egzersis yapalım:


In [3]:
a = np.array([1,2,3])
b= np.array([4,5,6])


In [4]:
a

array([1, 2, 3])

In [5]:
b

array([4, 5, 6])

In [7]:
print(a + b)

[5 7 9]


x ve y öğelerini ekler. [1+4, 2+5, 3+6]

In [8]:
print(a - b)

[-3 -3 -3]


x ve y öğelerin çıkarma işlemi uygular. [1-4, 2-5, 3-6]

In [9]:
print(a * b)

[ 4 10 18]


In [10]:
print(a / b)

[0.25 0.4  0.5 ]


a'in b kuvvetini alalım

In [12]:
print(a ** b)

[  1  32 729]


In [13]:
a.dot(b)

32

Dot işlemi 1 * 4 + 2 * 5 + 3 * 6

In [16]:
d = np.array([b])

In [18]:
d

array([[4, 5, 6]])

In [14]:
c = np.array([b, b**2])

In [15]:
c


array([[ 4,  5,  6],
       [16, 25, 36]])

ikinci dizinin birinci dizinin karesi olduğu bir dizi oluşturur.

In [19]:
c.shape

(2, 3)

c.shape, c'nin 2 satırı ve 3 sütunu olduğunu söylüyor. Bu iki boyutlu bir dizi.

In [20]:
c


array([[ 4,  5,  6],
       [16, 25, 36]])

In [21]:
c.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

c.T burada gösterildiği gibi satırı ve sütunu transpose eder/değiştirir.

In [22]:
c.T.shape

(3, 2)

In [23]:
e = np.array([-4, -2, 1, 3, 5])

In [24]:
e

array([-4, -2,  1,  3,  5])

In [25]:
e.sum()

3

In [26]:
e.max()

5

In [27]:
e.min()

-4

In [28]:
a.mean()

2.0

In [29]:
a.std()

0.816496580927726

e.mean() ve e.std() size sırasıyla aritmetik ortalama ve standart sapmayı verecektir.

argmax fonksiyonu dizinin en büyük elemanının indeksini, argmin fonksiyonu ise dizinin en küçük elemanının indeksini aşağıdaki gibi alır:

In [30]:
e.argmax()

4

In [31]:
e.argmin()

0


iki bilinmeyenli denklem nasıl çözülür?

In [2]:
import numpy as np

7* x0 + x1 = 13

x0 + 5 * x1 = 11

In [3]:
a = np.array([[7,1],[1,5]])

In [4]:
b = np.array([13,11])

In [5]:
x = np.linalg.solve(a,b)

In [6]:
x

array([1.58823529, 1.88235294])

![Divider05](images/divider05.png)

In [62]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\90530\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\90530\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>>

![Divider05](images/divider05.png)

In [63]:
#cheatsheet

In [64]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)

In [65]:
b.ndim

2

In [66]:
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],
 dtype = float)

In [67]:
c.ndim

3

In [68]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

b[[1, 0, 1, 0]][:,[0,1,2, 0]]
This line is performing two separate indexing operations:

The outer [1, 0, 1, 0] is an index array used to select rows from the array b.

array([[4., 5., 6.],
       [1.5, 2., 3.],
       [4., 5., 6.],
       [1.5, 2., 3.]])


The inner [:, [0, 1, 2, 0]] is an index array used to select columns from the previously selected rows.
Let's break it down further:

b[[1, 0, 1, 0]] selects rows from b based on the indices [1, 0, 1, 0]. So, it picks rows 1, 0, 1, and 0 in that order.

[:, [0, 1, 2, 0]] further selects columns from the previously selected rows. The : indicates that we're considering all the rows previously selected, and [0, 1, 2, 0] indicates the columns to be picked for each row.

For each row, it selects columns 0, 1, 2, and 0.

In [69]:
b[[1, 0, 1, 0]][:,[0,1,2, 0]]

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

b[[1, 0, 1, 0]][0, [0, 1, 2, 0]] performs further indexing on the rows obtained in the previous step.

array([[4., 5., 6.],
       [1.5, 2., 3.],
       [4., 5., 6.],
       [1.5, 2., 3.]])


b[[1, 0, 1, 0]] has already selected rows 1, 0, 1, and 0 as shown above.
[0, [0, 1, 2, 0]] indicates that from the rows obtained previously, you want to select the first row ([0]), and from that row, select columns [0, 1, 2, 0].
So, from the rows [4., 5., 6.] (which is row 0 after the initial selection), the indices [0, 1, 2, 0] are used for further indexing:

Column 0: 4.
Column 1: 5.
Column 2: 6.
Column 0 (again): 4.
Therefore, the final result is the array [4., 5., 6., 4.].

In [70]:
b[[1, 0, 1, 0]][0,[0,1,2, 0]]

array([4., 5., 6., 4.])

In [71]:
b[1][0]

4.0

In [72]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [73]:
c.sort(axis=0)

In [74]:
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

In [75]:
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

In [76]:
c.sort(axis=1)

In [77]:
c


array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

![Divider05](images/divider05.png)

### Statistical Cheatsheet

Numpy'ın temel istatistiksel işlemleri de vardır.

In [115]:
v

array([1, 2, 3, 4, 5])

In [116]:
v.min()

1

In [117]:
np.mean(v)

3.0

In [118]:
v.sum()

15

In [119]:
v.max()

5

In [120]:
np.var(v)

2.0

In [121]:
np.std(v)

1.4142135623730951

In [122]:
np.corrcoef(v)

1.0

istatistiki olmasa da:


In [123]:
v.argmin()

0

In [124]:
v.argmax()

4

In [125]:
import numpy as np

5 * x0 + x1 = 12


x0 +3 * x1 = 10

In [87]:
a = np.array([[5, 1], [1, 3]])
b = np.array([12, 10])

In [88]:
a

array([[5, 1],
       [1, 3]])

In [89]:
b

array([12, 10])

In [90]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])

![Divider05](images/divider05.png)

### array comparison/karşılaştırma

In [136]:
a


array([1, 2, 3, 4, 5])

In [137]:
b

array([3, 4, 5, 6, 7])

In [142]:
a == b # Öğe bazında karşılaştırma

array([False, False, False, False, False])

In [143]:
a < 2 # Öğe bazında karşılaştırma

array([ True, False, False, False, False])

In [144]:
 np.array_equal(a, b) #array bazında karşılaştırma

False

![Divider05](images/divider05.png)

### array kopyalama


In [127]:
a

array([1, 2, 3, 4, 5])

In [129]:
 h = a.view() # Aynı verilerle dizinin bir görünümünü oluşturun

In [130]:
h

array([1, 2, 3, 4, 5])

In [131]:
 np.copy(a) # kopyasını oluşturun

array([1, 2, 3, 4, 5])

In [132]:
j = a.copy() #derin kopyasını oluşturun

In [133]:
j

array([1, 2, 3, 4, 5])

![Divider05](images/divider05.png)

### yardım istemek

In [135]:
np.info(np.ndarray.dtype) # yardım isteme


Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


![Divider05](images/divider05.png)

🖖 Live Long and Prosper! ☺️

![Divider01](images/divider01.png)

#numpy #python #dataanalytics #datascience #dataanalysis #verianalizi #veribilimi #veribilim #veri #verianaliz #verimanipülasyonu #verigörselleştirme #makineöğrenme #derinöğrenme