
# Numpy : Oluşturma ve Biçimlendirme, Eleman İşlemleri, Koşullu Eleman İşlemleri, Hesaplamalı İşlemler

![NumPy](images/numpy.png)   **NumPy Module Ultimate Cheatsheet**

Numpy açık kaynaklı bir Python kütüphanesidir. Bu kütüphane veri bilimcileri için gereklidir. Pandas, Scipy gibi diğer bazı temel kütüphaneler Numpy kütüphanesi üzerine inşa edilmiştir. Numpy belgelerinde Numpy şu şekilde tanımlanır:

NumPy, Python'da bilimsel hesaplama için temel pakettir. Çok boyutlu bir dizi nesnesi, çeşitli türetilmiş nesneler (maskeli diziler ve matrisler gibi) ve diziler üzerinde matematiksel, mantıksal, şekil manipülasyonu, sıralama, seçme, I/O  , ayrık Fourier dönüşümleri, temel doğrusal cebir, temel istatistiksel işlemler, rastgele simülasyon ve çok daha fazlası dahil olmak üzere hızlı işlemler için çeşitli rutinler sağlayan bir Python kütüphanesidir.

Bilimsel hesaplamalar, arrayler/çok boyutlu arrayler ve matrisler. Listelere benzerdir, verimli veri saklama ve vektörel operasyonlar gerçekleştirilir. Fixed TYPE, sabit veri tipi saklar.

Navisgasyon için hücre seçili olarak hücre dışında:

`a` hücreden bir önce hücre aç

`b` hücreden bir sonra hücre aç

`x` kes, `c` kopyalar, `v` yapıştır

`m` markdown mode seç, `y` code mode seç

Hücre içinde ise:

`ctrl + x,c,v:` kes kopyala yapıştır

`shift + return`: shift + enter : hücreyi çalıştır ve sonraki hücreye geç/ilerle.

`ctrl  + return`: ctrl + enter: hücrede kal, odağı değiştirme ve hücreyi çalıştır.



Markdown modda:

#başlık, ##bir alt başlık, ###alt alt başlık, ####alt alt alt başlık

**bold yazar**

_italik yazar_

👉![WoW](images/wowjlab.jpg)👈

![Divider01](images/divider01.png)
    

Jupyter Lab ve not defterleri, metin ve görüntüleri içermek ve az önce gördüğünüz gibi güzel, insanlar tarafından okunabilen belgeler oluşturmak için şahane özelliklere sahip. Ancak asıl faydası kodla çalışmaktır. `Jupyter üç dile gönderme yapar. Python, R ve Julia kodlarını bu hücrelerde code modunda çalıştırabilirsiniz.` Şimdi `Numpy` kütüphanesini içe aktaracağız ve Python koduyla çalışmaya başlayacağız.  Öncelikle 'numpy'ı içe aktarmamız gerekiyor:

#### ***NumPy Array'i Oluşturmak***:

Tüm bu alıştırma için bir Jupyter Notebook kullandım. İlk önce Numpy'yi içe aktarın.

In [224]:
import numpy as np

Python'da 2 tane liste elemanlarını toplayıp yeni bir liste oluşturmak isteyelim, bunun için:

In [225]:
x = [ 1, 2, 3, 4]
y = [ 2, 3, 4, 5]

In [226]:
xy = []

for i in range(0, len(x)):
    xy.append(x[i] + y[i])
    
xy    


[3, 5, 7, 9]

NumPy'da ise array fonksiyonu ile iki tane array oluşturacağız:


In [227]:
a = np.array([1, 2, 3, 4])  
b = np.array([2, 3, 4, 5])

In [228]:
a + b #iki vektörün toplama işlemi

array([3, 5, 7, 9])

In [229]:
a * b #iki vektörün çarpma işlemi

array([ 2,  6, 12, 20])

`Voilaaa!` NumPy Magic!

![Divider02](images/divider02.png)

## Create Arrays / Diziler Oluşturma

Bir Numpy dizisi yapın. Bunu yapmak için bir Python listesi aktarmamız gerekiyor.

In [230]:
np.array([1 , 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

Burada integerlardan bir array oluşturduk.

In [231]:
a = np.array([1 , 2, 3, 4, 5])

In [232]:
type(a)

numpy.ndarray

Data Types
**********************************************************

> `np.int64` > Signed 64-bit integer types

> `np.float32` > Standard double-precision floating point

> `np.complex` > Complex numbers represented by 128 floats

> `np.bool` > Boolean type storing TRUE and FALSE values

> `np.object` > Python object type

> `np.string_` > Fixed-length string type

> `np.unicode_` > Fixed-length unicode type

***********************************************************

Şimdi float bir array yapalım.

In [233]:
np.array([3.14, 4, 2 , 13], dtype = "float32")

array([ 3.14,  4.  ,  2.  , 13.  ], dtype=float32)

Dikkat edin, Numpy tamsayıları/integerları otomatik olarak floata dönüştürdü!

**numpy sabit tip baskısı, içerde sadece tek tip veri tipi tutulur**

In [234]:
np.array([3.14, 4, 2 , 13], dtype = "int")

array([ 3,  4,  2, 13])

### Array Dimensions/Dizi Boyutları

![ArrayDimensions](images/arraydimensions.png)

In [235]:
a = np.array([1,2,3]) # 1D
b = np.array([(1.5,2,3), (4,5,6)], dtype = float) #2D
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float) #3D

In [236]:
a

array([1, 2, 3])

In [237]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [238]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

### Array İnceleme

> `a.shape` : Array boyutları

> `len(a)` : Arrayin uzunluğu

> `b.ndim` : Array boyutlarının sayısı

> `c.size` : Array elemanlarının sayısı

> `b.dtype` : Array elemanlarının veri türü

> `b.dtype.name` : Veri türünün adı

> `b.astype(int)` : Bir arrayi farklı bir türe dönüştürür


In [239]:
a.shape #'a' dizisinin şeklini/biçimini bulun

(3,)

In [240]:
len(a) # Dizinin uzunluğunu bulun

3

In [241]:
b.ndim #b dizisinin boyutlarını bulun

2

In [242]:
c.size # dizinin büyüklüğü eleman sayısı ile ilişkili

12

In [243]:
b.dtype #dizinin veri tipi

dtype('float64')

In [244]:
b.dtype.name #dizinin veri tipi ismi

'float64'

In [245]:
b.astype(int) # dizinin veri tipini değiştirme - float to integer

array([[1, 2, 3],
       [4, 5, 6]])

In [246]:
len(b) 

2

'b' dizisi iki boyutlu bir dizidir. Yani dizinin uzunluğu, içindeki eleman sayısı anlamına gelmez. Uzunluk, içindeki tek boyutlu dizilerin sayısı veya içindeki satırların sayısı anlamına gelir. 
İki satırı vardır. Yani uzunluk 2'dir.

![Divider02](images/divider02.png)

### sıfırdan array oluşturma işlemleri / initial placeholders

Numpy arraylerini sıfırdan, listelerden ve başa veri türlerinden oluşturabiliriz. Numpy Array bir veri tipidir.

> ##### 10 tane sıfırdan array oluştur, zeros fonksiyonu

In [247]:
np.zeros(10 , dtype =int) 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

> ##### 3*5 1'lerden array/matris oluştur, ones fonksiyonu

In [248]:
np.ones((3,5), dtype = int) # 3*5 1'lerden array/matris oluştur, ones fonksiyonu

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

> ##### 3*5 3'lerden array/matris oluştur, full fonksiyonu

In [249]:
np.full((3, 5), 3) # 3*5 3'lerden array/matris oluştur, full fonksiyonu

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

> ##### 2X2 birim matris oluşturma - eye fonksiyonu


In [250]:
 f = np.eye(2, dtype=int)

In [251]:
f #  2X2 birim matris oluşturma

array([[1, 0],
       [0, 1]])

In [252]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [253]:
z = np.array([3, 5, 7]) # istersek diagonal sayıları farklı yapabiliriz
np.diag(z)

array([[3, 0, 0],
       [0, 5, 0],
       [0, 0, 7]])

> ##### arange fonksiyonu - Eşit aralıklı değerlerden oluşan bir dizi oluştur (adım/step değeri)   - sıfırla 33 arasında 3er atlayarak

In [254]:
np.arange(0, 33 ,3)    #Eşit aralıklı değerlerden oluşan bir dizi oluştur (adım/step değeri)   - sıfırla 33 arasında 3er atlayarak

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [255]:
np.arange(10)**2 #Bu durumda 0-9'a bir aralık istedik ve çıktı dizisinde 0'dan 9'a kadar olan sayıların karesini aldık.

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [256]:
np.identity(5) #identity matrisi, Bu, tüm elemanların 0 olduğu ve yalnızca diagonal elemanların bir olduğu beşe beşlik bir matris

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

> ##### iki sayı içerisinde belirtilen aralıkta eşit aralıklı on tane değer oluşturma - linspace fonksiyonu

In [257]:
np.linspace(0, 1, 10)   # Belirtilen aralıkta eşit aralıklı sayıları döndür

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

> ##### oluşturmak istenen sayılar belirli bir dağılım yapısına sahip olsun, belirli bir ortalama, belirli bir standart sapma verilerek - random.normal fonksiyonu

In [258]:
np.random.normal(10, 4, (3,4))   #ortalaması 10 standart sapması 4 olacak şekilde

array([[12.76772579, 12.3569191 , 10.76060525,  6.32043815],
       [13.0359451 ,  7.60063632,  9.93826149, 15.04716018],
       [13.97761075, 14.097816  , 16.63950871, 12.17352853]])

> #####  random.randit fonksiyonu

In [259]:
np.random.randint(0, 10 ,(3 , 3))

array([[5, 4, 2],
       [4, 1, 4],
       [8, 0, 9]])

#NumPy Özellikleri

> **ndim** : _boyut sayısı_

> shape : boyut bilgisi

> size : toplam eleman sayısı

> dtype : array veri tipi

In [260]:
import numpy as np

In [261]:
np.random.randint(10, size = 10) #Rastgele tamsayılar üretmek için randint fonksiyonu kullanılır.

array([6, 7, 7, 9, 2, 4, 1, 9, 4, 8])

![Divider05](images/divider05.png)

In [262]:
a = np.random.randint(10, size = 10)

In [263]:
a.ndim

1

In [264]:
a.shape

(10,)

In [265]:
a.shape[0] # bu örnek için a dizisinin ilk (ve tek) boyutunun biçimini çıkarır. Bu durumda 10'a eşdeğer olacaktır. Size birinci eksen (matris olarak düşünürseniz, satırlar) boyunca bulunan elemanların sayısını söyler.

10

In [266]:
a.size

10

In [267]:
a.dtype

dtype('int32')

In [268]:
b = np.random.randint(10, size = (3, 5))

In [269]:
b

array([[2, 2, 4, 4, 4],
       [2, 1, 8, 8, 6],
       [3, 5, 5, 5, 1]])

In [270]:
b.ndim

2

In [271]:
b.shape

(3, 5)

In [272]:
b.size

15

In [273]:
b.dtype

dtype('int32')

![Divider05](images/divider05.png)

### Yeniden Şekillendirme - Reshaping - Arrayleri yeniden düzenleme

In [274]:
import numpy as np

In [275]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

> ##### tek boyutlu bir arrayi matrise dönüştürme  - np.arange().reshape()

In [276]:
np.arange(1, 10).reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [277]:
a = np.arange(1, 10)

In [278]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [279]:
a.ndim

1

In [280]:
a.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [281]:
b = a.reshape((1,9))  #tek boyutlu bir arrayi iki boyutlu bir matrise çevirme ama tek boyutlu bilgiside olduğu şekilde kalsın

In [282]:
b.ndim

2

Bir arrayi yeniden düzenlemenin veya yeniden şekillendirmenin farklı yolları var:

In [283]:
r = np.arange(0, 45, 3)
r

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42])

In [284]:
r.reshape(3, 5)

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42]])

In [285]:
t = np.arange(0, 45, 3)
t

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42])

In [286]:
t.resize(3,5)
t

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42]])

In [287]:
t.ravel() #tek boyuta geri dönmek için

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42])

In [288]:
k = np.array([1,5,9])
k

array([1, 5, 9])

In [289]:
k.resize(3,1)
k

array([[1],
       [5],
       [9]])

In [290]:
k.resize(1,3) #orijinal olarak tek boyutluydu , sonuçta iki boyuta evrildi
k

array([[1, 5, 9]])

In [291]:
e = np.array([[1,2,3,4], [5,6,7,8]])
e

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [422]:
q = e.reshape(4,2) #iki boyutluyu reshape yapalım
q

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [424]:
y = e.reshape(4, -1) # büyük bir veri var elinizde ama sadece bir boyutu biliyorsunuz
y

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Kafa karıştırıcı mı görünüyor? Çok büyük bir arrayiniz veya veri setiniz olduğunu hayal edin. Yeniden şekillendirmeden önce yalnızca bir boyutu biliyorsunuz. Yani, yeniden şekillendirme yönteminde bu bir boyutu girersiniz ve diğer boyut için -1'i kullanırsınız. Bu şekilde Numpy'nin kendisi diğer boyutu çözecektir.

In [426]:
y.T #Transpose the array

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

Bu yönteme transpose deniyor. Bir dizi veya matris üzerinde transpose kullandığınızda, yalnızca boyutları değiştirir. 2×3 matris 3×2 olur, 3×6 matris 6×3 olur veya 1×3 matris 3×1 olur.

### concatenation - birleştirme işlemleri

In [293]:
import numpy as np

In [294]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [295]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [296]:
z = np.array([7, 8, 9])

In [297]:
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

> #iki boyutlu birleştirme - tek boyutlu array vektördür, iki ve daha fazla boyutlu array is matristir.

In [298]:
a = np.array([[1, 2, 3], [4, 5, 6]])   #iki boyutlu arrayi/matrisi manuel oluşturma

In [299]:
a

array([[1, 2, 3],
       [4, 5, 6]])

> ##### a ile a'yı birleştirme (satır bazında birleştirme)  axis = 0 satır bazında(row sayısını artırır) , axis = 1 sutun bazında(column sayısını artırır)

In [300]:
np.concatenate([a, a]) 

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

> #sutun bazında birleştirme

In [301]:
np.concatenate([a, a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### Append, Insert, Delete,  Sort ve Flip

> `append`

In [435]:
np.append([7,3], [[2,5], [1, 4]]) #append

array([7, 3, 2, 5, 1, 4])

In [437]:
np.append([1, 2, 3], [[4, 5], [6,7]])  #default olarak axis-1 horizantal yönde append yapılıyor

array([1, 2, 3, 4, 5, 6, 7])

In [438]:
np.append([[1,7,5], [4,7,6]], [[1,2,3]], axis=0) #axis-0 vertical yönde satır bazında

array([[1, 7, 5],
       [4, 7, 6],
       [1, 2, 3]])

> `insert`

In [440]:
a = np.array([[7, 7], [3, 4], [5, 6]])
a

array([[7, 7],
       [3, 4],
       [5, 6]])

In [442]:
np.insert(a, 0, 9) #insert 9 elemanını başlangıca insert yapalım

array([9, 7, 7, 3, 4, 5, 6])

👆 (a, 0, 9)'da a arraydir, 0 öğenin eklenmesini istediğimiz konumdur ve 9 da eklenmesi gereken öğedir.

In [444]:
np.insert(a, 0, 8, axis=1) # axis-1 horizantal yönde 8'lerden bir column eklenir

array([[8, 7, 7],
       [8, 3, 4],
       [8, 5, 6]])

In [447]:
np.insert(a, 0, 8, axis=0) # axis - 0 vertical yönde 8'lerden  bir row eklenir

array([[8, 8],
       [7, 7],
       [3, 4],
       [5, 6]])

> `delete`

In [449]:
a= np.array([[1, 3, 5, 8], [3, 1, 9, 7], [9, 10, 7, 3]])
a

array([[ 1,  3,  5,  8],
       [ 3,  1,  9,  7],
       [ 9, 10,  7,  3]])

In [451]:
np.delete(a, [1, 3, 5]) #1. 3. ve 5. indextekiler silinir. Ekleme işlemi gibi silme işlemi de arrayi düzleştirir.

array([ 1,  5,  3,  9,  7,  9, 10,  7,  3])

In [454]:
a.flatten() #a arrayini düzleştir

array([ 1,  3,  5,  8,  3,  1,  9,  7,  9, 10,  7,  3])

In [456]:
np.delete(a, 1, 1) # (a, 1, 1) girişinde a diziyi, 1 silmek istediğimiz sütunun indeksini ve sondaki 1 ise ekseni belirler

array([[1, 5, 8],
       [3, 9, 7],
       [9, 7, 3]])

In [459]:
np.delete(a, 1, 0) # a arrayi, 1 silmek istediğimiz satırı ve sondaki 0 ise axisi vertical yönde satır bazında belirler

array([[ 1,  3,  5,  8],
       [ 9, 10,  7,  3]])

> `sort`

In [463]:
s = np.random.randint(1,16,(4,4))
s

array([[11,  3, 14, 13],
       [ 7,  1,  7, 14],
       [ 6,  7, 10,  2],
       [ 4, 11, 12,  9]])

In [464]:
np.sort(s)

array([[ 3, 11, 13, 14],
       [ 1,  7,  7, 14],
       [ 2,  6,  7, 10],
       [ 4,  9, 11, 12]])

In [467]:
np.sort(s, axis=None) # axis none olduğunduğunda arrayi düzleştirir ve sort yapar

array([ 1,  2,  3,  4,  6,  7,  7,  7,  9, 10, 11, 11, 12, 13, 14, 14])

In [468]:
np.sort(s, axis=0)

array([[ 4,  1,  7,  2],
       [ 6,  3, 10,  9],
       [ 7,  7, 12, 13],
       [11, 11, 14, 14]])

In [469]:
np.sort(s, axis=1)

array([[ 3, 11, 13, 14],
       [ 1,  7,  7, 14],
       [ 2,  6,  7, 10],
       [ 4,  9, 11, 12]])

> `flip`

In [478]:
f = np.arange(0,16).reshape(4,4)

In [479]:
f

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [483]:
np.flip(f, 0)  #flip axis 0 yönünde

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [482]:
np.flip(f, 1) #flip  axis 1 yönünde

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])


### Array tekrarlama - Array Repeat

In [302]:
np.array([ 3, 5, 7, 9])


array([3, 5, 7, 9])

Dizinin tamamını tekrarlamak istiyorsanız

In [303]:
np.array([ 3, 5, 7, 9]*4)

array([3, 5, 7, 9, 3, 5, 7, 9, 3, 5, 7, 9, 3, 5, 7, 9])

Element bazında tekrarın nasıl yapılacağı 

In [304]:
np.repeat([ 3, 5, 7, 9], 4)

array([3, 3, 3, 3, 5, 5, 5, 5, 7, 7, 7, 7, 9, 9, 9, 9])

In [305]:
_2dtekr = np.array([[3,5,7,9]]) #iki boyutlu bir array yapalım ve 4 kez satır bazında tekrarlayalım

In [306]:
np.repeat(_2dtekr,4,axis=0) #axis(eksen) = 0. Yani tekrar eksen-0 yönünde veya satırlar yönünde gerçekleşti.

array([[3, 5, 7, 9],
       [3, 5, 7, 9],
       [3, 5, 7, 9],
       [3, 5, 7, 9]])

In [307]:
np.repeat(_2dtekr,4,axis=1) #sütun bazında, Eksen 1 sütunların yönünü gösterir

array([[3, 3, 3, 3, 5, 5, 5, 5, 7, 7, 7, 7, 9, 9, 9, 9]])

### Array ayırma - Splitting

In [308]:
import numpy as np

In [309]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])

In [310]:
np.split(x, [3, 5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [311]:
a, b, c = np.split(x, [3, 5])

In [312]:
print(a , b, c)

[1 2 3] [99 99] [3 2 1]


In [313]:
a

array([1, 2, 3])

In [314]:
b

array([99, 99])

In [315]:
c

array([3, 2, 1])

> #iki boyutlu ayırma

In [316]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

> ##### vertical split

In [317]:
np.vsplit(m, [2])  #vertical split

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [318]:
ust ,alt = np.vsplit(m, [2])

In [319]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [320]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [321]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

> #horizontal split

In [322]:
np.hsplit(m , [2]) #horizontal split

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [323]:
sag, sol = np.hsplit(m , [2])

In [324]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [325]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [428]:
n1 = [[2, 5, 8, 7], [6, 5, 2, 1]]
n2 = [4, 0, 9, 5]

In [429]:
np.vstack([n1, n2])  #vstack

array([[2, 5, 8, 7],
       [6, 5, 2, 1],
       [4, 0, 9, 5]])

In [430]:
np.vstack([n1, n2, n2])  #Bunları istediğiniz kadar stackleyebilirsiniz/istifleyebilirsiniz.

array([[2, 5, 8, 7],
       [6, 5, 2, 1],
       [4, 0, 9, 5],
       [4, 0, 9, 5]])

In [431]:
np.array(n1)

array([[2, 5, 8, 7],
       [6, 5, 2, 1]])

In [432]:
n3 = np.ones((2,3))
n3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [433]:
np.hstack([n1, n3])  #horizantal stack

array([[2., 5., 8., 7., 1., 1., 1.],
       [6., 5., 2., 1., 1., 1., 1.]])

![Divider05](images/divider05.png)

### Sorting - Sıralama

In [326]:
import numpy as np

In [327]:
v = np.array([2, 1, 4, 3, 5])

In [328]:
v

array([2, 1, 4, 3, 5])

In [329]:
np.sort(v) #numpy içerisinden çağrıldığında arrayin orijinal yapısını bozmaz

array([1, 2, 3, 4, 5])

In [330]:
v

array([2, 1, 4, 3, 5])

In [331]:
v.sort() #nesneden çağrıldığında yapısını alter eder

In [332]:
v

array([1, 2, 3, 4, 5])

> #iki boyutlu sorting

In [333]:
m = np.random.normal(20 , 5, (3, 3)) #ortalaması 20 standart sapması 5 olabilecek şekilde 

In [334]:
m

array([[19.729877  , 25.00682366, 22.48306638],
       [22.11851838, 15.62072915, 18.83734856],
       [14.78102506, 17.77085194, 18.59050694]])

In [335]:
np.sort(m, axis = 1)  # her satırı küçükten büyüğe olacak şekilde sıralıyor

array([[19.729877  , 22.48306638, 25.00682366],
       [15.62072915, 18.83734856, 22.11851838],
       [14.78102506, 17.77085194, 18.59050694]])

In [336]:
np.sort(m, axis = 0)  # her sutunu küçükten büyüğe olacak şekilde sıralıyor

array([[14.78102506, 15.62072915, 18.59050694],
       [19.729877  , 17.77085194, 18.83734856],
       [22.11851838, 25.00682366, 22.48306638]])

![Divider05](images/divider05.png)

### ELEMAN İŞLEMLERİ - Alt Kümeleme, Dilimleme, İndeksleme ( Subsetting, Slicing, Indexing ) 

In [337]:
#ındex ile elemanlara erişme işlemleri

In [338]:
import numpy as np

In [339]:
a = np.random.randint(10, size = 10)
a

array([5, 3, 6, 3, 6, 9, 6, 3, 9, 4])

In [340]:
a[0] # 0. dizindeki öğeyi seçin

5

In [341]:
a[-1]

4

In [342]:
a[0] = 100

In [343]:
a

array([100,   3,   6,   3,   6,   9,   6,   3,   9,   4])

> #iki boyutluda elemana erişim işlemi

In [344]:
m = np.random.randint(10, size = (3,5))
m

array([[0, 5, 6, 9, 1],
       [4, 8, 3, 9, 7],
       [8, 2, 6, 4, 4]])

Satır 1 sütun 2'deki öğeyi seçin
  (m[1][2]'ye eşdeğer)

In [345]:
m[1,2]

3

In [346]:
m[0,0]

0

In [347]:
m[1,1]

8

In [348]:
m[2, 2]

6

In [349]:
m[1,4]

7

In [350]:
m[1,4] = 2

In [351]:
m

array([[0, 5, 6, 9, 1],
       [4, 8, 3, 9, 2],
       [8, 2, 6, 4, 4]])

In [352]:
m[1,4] = 2.2
m

array([[0, 5, 6, 9, 1],
       [4, 8, 3, 9, 2],
       [8, 2, 6, 4, 4]])

> #Array alt küme işlemleri - slicing

In [353]:
import numpy as np

In [354]:
a = np.arange(20, 30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [355]:
a[0:3] #0 , 1 ve 2 dizinindeki öğeleri seç

array([20, 21, 22])

In [356]:
a[:3]

array([20, 21, 22])

In [357]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [358]:
a[1::2] #1. indexten başlayarak ikişer atlayarak

array([21, 23, 25, 27, 29])

In [359]:
a[0::2]

array([20, 22, 24, 26, 28])

In [360]:
a[2::2]

array([22, 24, 26, 28])

In [361]:
a[0::3]

array([20, 23, 26, 29])

> ##### iki boyutlu slice işlemleri

In [362]:
import numpy as np
m = np.random.randint(10, size = (5,5))

In [363]:
m

array([[1, 4, 8, 0, 9],
       [9, 2, 1, 6, 9],
       [6, 5, 6, 2, 9],
       [6, 8, 3, 4, 7],
       [7, 8, 1, 9, 7]])

In [364]:
m[2,3] #subsetting

2

In [365]:
m[0:1] #slicing

array([[1, 4, 8, 0, 9]])

In [366]:
m[0:2,1] # 1. sütundaki 0 ve 1. satırlardaki öğeleri seçin

array([4, 2])

In [367]:
m[: ,1] #ikinci sutuna erişme

array([4, 2, 5, 8, 8])

In [368]:
m[0, :]

array([1, 4, 8, 0, 9])

In [369]:
m[0]

array([1, 4, 8, 0, 9])

In [370]:
m[1, :]

array([9, 2, 1, 6, 9])

In [371]:
m[0:2, 0:3]

array([[1, 4, 8],
       [9, 2, 1]])

In [372]:
m[::, :2]

array([[1, 4],
       [9, 2],
       [6, 5],
       [6, 8],
       [7, 8]])

In [373]:
m[:, 0:2]

array([[1, 4],
       [9, 2],
       [6, 5],
       [6, 8],
       [7, 8]])

In [374]:
m

array([[1, 4, 8, 0, 9],
       [9, 2, 1, 6, 9],
       [6, 5, 6, 2, 9],
       [6, 8, 3, 4, 7],
       [7, 8, 1, 9, 7]])

In [375]:
m[1:3, 0:2]

array([[9, 2],
       [6, 5]])

> #alt küme üzerinde işlem yapmak

In [376]:
import numpy as np

In [377]:
a = np.random.randint(10 , size = (5, 5))
a

array([[9, 1, 8, 2, 6],
       [9, 9, 1, 1, 0],
       [3, 0, 4, 4, 9],
       [5, 5, 0, 4, 3],
       [9, 6, 2, 7, 7]])

In [378]:
alt_a = a[0:3, 0:2]
alt_a

array([[9, 1],
       [9, 9],
       [3, 0]])

In [379]:
alt_a[0,0] = 99999
alt_a[1,1] = 888

In [380]:
alt_a

array([[99999,     1],
       [    9,   888],
       [    3,     0]])

In [381]:
a

array([[99999,     1,     8,     2,     6],
       [    9,   888,     1,     1,     0],
       [    3,     0,     4,     4,     9],
       [    5,     5,     0,     4,     3],
       [    9,     6,     2,     7,     7]])

In [382]:
m = np.random.randint(10 , size = (5, 5))
m

array([[3, 4, 5, 3, 6],
       [3, 1, 0, 2, 1],
       [6, 1, 9, 4, 8],
       [1, 5, 4, 2, 6],
       [4, 3, 3, 1, 6]])

In [383]:
alt_b = m[0:3, 0:2].copy() #copy yaptığımız ana kümeden bağımsızlaşır

In [384]:
alt_b

array([[3, 4],
       [3, 1],
       [6, 1]])

In [385]:
alt_b[0,0] = 99999
alt_b[1,1] = 888

In [386]:
alt_b

array([[99999,     4],
       [    3,   888],
       [    6,     1]])

In [387]:
m

array([[3, 4, 5, 3, 6],
       [3, 1, 0, 2, 1],
       [6, 1, 9, 4, 8],
       [1, 5, 4, 2, 6],
       [4, 3, 3, 1, 6]])

> **#fancy index ile elemanlara erişmek**

In [388]:
import numpy as np

In [389]:
v =  np.arange(0, 30 ,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [390]:
v[1]

3

In [391]:
v[3]

9

In [392]:
v[5]

15

In [393]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [394]:
al_getir = [1, 3, 5]

In [395]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [396]:
v[al_getir] #işte buna fancy index deniyor

array([ 3,  9, 15])

> ##### iki boyutlu fancy index işlemi

In [397]:
m = np.arange(9).reshape((3,3))

In [398]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [399]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [400]:
m[satir, sutun]

array([1, 5])

> #basit index ile fancy index

In [401]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [402]:
m[0,[1,2]]

array([1, 2])

> #slice ile fancy index

In [403]:
m[0: , [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

### Koşullu Eleman İşlemleri

In [404]:
import numpy as np

In [405]:
v = np.array([1, 2, 3, 4, 5])

In [406]:
v > 5

array([False, False, False, False, False])

In [407]:
v < 3

array([ True,  True, False, False, False])

In [408]:
v[v < 3] #boolean indexing

array([1, 2])

In [409]:
v[v >3]

array([4, 5])

In [410]:
v[v >= 3]

array([3, 4, 5])

In [411]:
v[v <= 3]

array([1, 2, 3])

In [412]:
v[ v == 3]

array([3])

In [413]:
v[v != 3]

array([1, 2, 4, 5])

In [414]:
v

array([1, 2, 3, 4, 5])

In [415]:
v * 2

array([ 2,  4,  6,  8, 10])

In [416]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [417]:
v * 5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [418]:
v**2

array([ 1,  4,  9, 16, 25])

🧠🧠🧠🧠🧠 > **Matrisin satır ve sütunlarının bir alt kümesini seçin**

`Fancy Index Örneği`


In [419]:
 b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
    

In [420]:
b


array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [421]:
b[[1, 0, 1, 0]][:,[0,1,2,0]]

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

Row Indexing (b[[1, 0, 1, 0]]):

This part of the indexing is selecting rows from the array b based on the provided list of row indices [1, 0, 1, 0]. The resulting array would have the rows from the original array in the order specified by the list.

The first row is the row at index 1: [4, 5, 6].
The second row is the row at index 0: [1.5, 2, 3].
The third row is again the row at index 1: [4, 5, 6].
The fourth row is again the row at index 0: [1.5, 2, 3].

Satır İndeksleme (b[[1, 0, 1, 0]]):

Bu kısım, belirtilen satır indisleri [1, 0, 1, 0] kullanılarak diziden satırları seçiyor. Sonuç dizisi, orijinal dizide belirtilen sırayla satırları içerir.

İlk satır, 1. indexteki satırdır: [4, 5, 6].
İkinci satır, 0. indexteki satırdır: [1.5, 2, 3].
Üçüncü satır, tekrar 1. indexteki satırdır: [4, 5, 6].
Dördüncü satır, tekrar 0. indexteki satırdır: [1.5, 2, 3].

`[[4. 5. 6.]`

`[1.5 2. 3.]`
 
`[4. 5. 6.]`
 
`[1.5 2. 3.]]`

Column Indexing ([:, [0, 1, 2, 0]]):

This part of the indexing is selecting columns from the array obtained from the previous step based on the provided list of column indices [0, 1, 2, 0]. The resulting array would have columns from the original array in the order specified by the list.

The first column is the column at index 0: [4, 1.5, 4, 1.5].
The second column is the column at index 1: [5, 2, 5, 2].
The third column is the column at index 2: [6, 3, 6, 3].
The fourth column is again the column at index 0: [4, 1.5, 4, 1.5].

Sütun İndeksleme ([:, [0, 1, 2, 0]]):

Bu kısım, önceki adımdan elde edilen diziden belirtilen sütun indisleri [0, 1, 2, 0] kullanılarak sütunları seçiyor. Sonuç dizisi, orijinal diziden belirtilen sırayla sütunları içerir.

İlk sütun, 0. indexteki sütundur: [4, 1.5, 4, 1.5].
İkinci sütun, 1. indexteki sütundur: [5, 2, 5, 2].
Üçüncü sütun, 2. indexteki sütundur: [6, 3, 6, 3].
Dördüncü sütun, tekrar 0. indexteki sütundur: [4, 1.5, 4, 1.5].


 
 
`[[4. 5. 6. 4.]`

`[1.5 2. 3. 1.5]`
 
`[4. 5. 6. 4.]`
 
`[1.5 2. 3. 1.5]]`



So, the final result is a 4x4 array where rows and columns are selected based on the specified indices. The row indices are [1, 0, 1, 0], and the column indices are [0, 1, 2, 0]. This advanced indexing allows you to extract and rearrange elements from an array in a more flexible way.

Sonuç olarak, sonuç 4x4 boyutunda bir dizi olup, satır ve sütunlar belirtilen indislerle seçilmiştir. Satır indisleri [1, 0, 1, 0] ve sütun indisleri [0, 1, 2, 0]. Bu gelişmiş indeksleme, bir diziden elemanları çıkarmak ve düzenlemek için daha esnek bir yöntem sunar.

🖖 Live Long and Prosper! (2. bölümde devam ediyor...)

![Divider05](images/divider05.png)